language: node_js
sudo: false

node_js:
  - "0.12"
  
install:
  - cd jshint-server && npm install && cd ../jshint && npm install && cd ..
  
script:
  - cd jshint-server && npm run compile && cd .. && npm run compile